# If you are using a dongle, custom ZMK configuration options should go in this
# file. If you are not using a dongle (using the left as central), this file is
# ignored.
CONFIG_ZMK_RGB_UNDERGLOW=y

/* Add this block to your .conf file */
/ {
    chosen {
        zmk,underglow = &underglow_leds;
    };

    underglow_leds: underglow_leds {
        compatible = "ws2812-gpio";
        label = "UNDERGLOW_LEDS";
        /* Pin D6 (P0.10) is a common choice for nRF52840 controllers */
        gpio-pin = <10>; 
        /* CHECK THIS: ErgoDox usually has 36 LEDs (18 per half) or 32 LEDs. */
        chain-length = <4>;
        color-mapping = <WS-2812-GRB>;
    };
};
